### ISSUE TITLE
i need ios version 

### ISSUE THREAD

**Issue by buzai** [tsingsee/EasyRTSPLive#2]

**Comment by Tsingsee-Seven** [comment]
seven@tsingsee.com

**Comment by Tsingsee-Seven** [comment]
&nbsp;
 &nbsp;
 您好，我是青犀产品负责人，你可以叫我Seven，我们在安徽省合肥市高新区，我的电话联系方式为：18855112323。
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"buzai"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年3月13日(星期五) 晚上9:13
 收件人:&nbsp;"tsingsee/EasyRTSPLive"<EasyRTSPLive@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[tsingsee/EasyRTSPLive] i need ios version (#2)
